[package]
name = "rbac_linter"
version = "0.1.0"
authors = ["Andrew Helwer <ahelwer@disjunctive.llc>"]
description = "Teleport RBAC rule analysis using Z3"
repository = "https://github.com/ahelwer/teleport-z3"

[dependencies]
z3-sys = {version="0.7.1", features = ["static-link-z3"]}
