name: Build & Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.0
      - name: Restore Python packages
        uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
      - name: Run Python tests
        run: pytest
      - name: Run Python role equivalence check script
        run: python role_equivalence_check.py data/role.yml data/role2.yml --debug
      - name: Run Python role query script
        run: python role_query.py data/nodes.yml data/roles.yml --users data/users.yml --debug
